### PR TITLE
Gracefully handle cfimage errors

### PR DESCRIPTION
**Pull request by jsieber-aca**
We ran into some errors when this plugin tried to read some of our associated images, so this fix helps to gracefully handles that situation.

### CODE REVIEW

**Comment by al3x-edge** [comment]
@jsieber-aca Nice catch =] -- Sorry that caused issue for you.  Thanks for the PR.  I imagine that this issue is also in TwitterCards (where this was forked from) as well if you would don't mind donating more time.

/cc @PeterBowater

**Comment by jsieber-aca** [comment]
@al3x-edge What is best method for getting these back to the original project. Can you do a pull request with both or our changes to Peter?

**Comment by al3x-edge** [comment]
Would just need to fork the project and then apply the fix to his master branch. At this point I've deviated too much from his master.  I can certainly move the change back upstream if you don't want to though.  Ultimately, it would be nice to have a single plugin that handles all "cards" and such.  I believe there are more services with special metas as well.

**Comment by jsieber-aca** [comment]
I can do that.

**Pull request merged**
