### PR TITLE
Change fb:admins to fb:app_id

### PR DESCRIPTION
**Pull request by jsieber-aca**
Update to meta property for fb:admins to fb:app_id. When using the url debugger, I found I had to change fb:admins property value to fb:app_id.

### CODE REVIEW

**Comment by al3x-edge** [comment]
Bit late on this merge, but LGTM :+1:

**Comment by al3x-edge** [comment]
Btw @jsieber-aca, if that is your dog -- beautiful >.<

**Comment by jsieber-aca** [comment]
@al3x-edge  thanks, she is no longer with us, but was a great dog.

**Comment by al3x-edge** [comment]
@jsieber-aca Aww. Bummer. Sad to hear :cry:
What breed was she?
Here's the one in our family that melts me:
11061328_10206333412234097_3479319832755994381_n

**Comment by jsieber-aca** [comment]
@al3x-edge She was a Siberian Husky. She was a great dog and companion for 15 years. Looks like yours is a Siberian as well? Great looking dog.

**Comment by al3x-edge** [comment]
Ah. A good life! She is my sister's. Thanks =]  Cheers to the dogs -- :beers:

P.S. Thanks for the PR.

**Comment by jsieber-aca** [comment]
you bet! Have a good one.

**Pull request merged**
